version: "3"
services:
  api:
      build: api-container/
      ports:
        - 9090:9090
  gui:
      build: gui-container/
      ports:
        - 80:80
      links:
        - api:apiserver

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
      environment:
        ELASTICSEARCH_USER: admin
        ELASTICSEARCH_PASS: admin
      ports:
        - "9200:9200"

  kibana:
      image: docker.elastic.co/kibana/kibana:7.2.0
      container_name: kibana
      environment:
        SERVER_NAME: localhost
        ELASTICSEARCH_URL: http://elasticsearch1:9200/
        ELASTICSEARCH_USER: admin
        ELASTICSEARCH_PASS: admin
      ports:
        - "5601:5601"
    # volumes:
    #     type: volume
    #     source: logs
    #     target: /var/log
